CREATE VIEW RELATORIO AS 
SELECT C.NOME, 
       C.SEXO, 
	   C.EMAIL, 
	   T.TIPO, 
	   T.NUMERO, 
	   E.BAIRRO, 
	   E.CIDADE, 
	   E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT * FROM RELATORIO;

/* VERIFICANDO UMA VIEW */
SHOW TABLES;

/* APAGANDO UMA VIEW */
DROP VIEW RELATORIO;

/* APAGANDO UMA VIEW */
DROP VIEW RELATORIO;

/* INSERINDO UM PREFIXO */
CREATE VIEW V_RELATORIO AS 
SELECT C.NOME, 
       C.SEXO, 
	   IFNULL(C.EMAIL, 'CLIENTE SEM EMAIL') AS "E-MAIL",
	   T.TIPO, 
	   T.NUMERO, 
	   E.BAIRRO, 
	   E.CIDADE, 
	   E.ESTADO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

/* SELECT DENTRO DE VIEW */
SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;
